import type { Metadata } from "next";
import Link from "next/link";
import { ChevronRight, CircleUserRound, Landmark, LogOut, Palette, Target, WalletCards } from "lucide-react";
import { signOutAction } from "@/app/(auth)/actions";
import { PageContainer } from "@/components/app/mobile-ui";
import { ThemeToggle } from "@/components/app/theme-toggle";
import { SettingsForm } from "@/components/forms/settings-form";
import { Button } from "@/components/ui/button";
import { getFinanceBooks } from "@/lib/data/books";
import { getUserProfile } from "@/lib/data/profile";

export const metadata: Metadata = { title: "Ещё" };

export default async function SettingsPage() {
  const [profile, books] = await Promise.all([getUserProfile(), getFinanceBooks()]);
  return <PageContainer className="grid gap-7"><header><p className="text-sm text-muted-foreground">Профиль и приложение</p><h1 className="mt-1 text-[1.75rem] font-bold">Ещё</h1></header><section><h2 className="mb-3 text-lg font-semibold">Личные финансы</h2><div className="overflow-hidden rounded-[var(--radius-card)] border border-border bg-panel shadow-[var(--shadow-panel)]"><MoreLink href="/app/wallets" title="Кошельки и категории" icon={WalletCards} /><MoreLink href="/app/budgets" title="Бюджеты" icon={Target} /><div className="flex min-h-16 items-center gap-3 px-4"><span className="grid size-10 place-items-center rounded-xl bg-muted text-primary"><Landmark aria-hidden className="size-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">Финансовые профили</span><span className="mt-0.5 block text-xs text-muted-foreground">{books.length} {books.length === 1 ? "профиль" : "профиля"}</span></span></div></div></section><section className="rounded-[var(--radius-card)] border border-border bg-panel p-5 shadow-[var(--shadow-panel)]"><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Тема</h2><p className="mt-1 text-sm text-muted-foreground">Светлая или тёмная</p></div><ThemeToggle /></div></section><section className="rounded-[var(--radius-card)] border border-border bg-panel p-5 shadow-[var(--shadow-panel)]"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-muted text-primary"><CircleUserRound aria-hidden className="size-5" /></span><div><h2 className="text-lg font-semibold">Профиль</h2><p className="mt-1 text-sm text-muted-foreground">Язык, валюта и часовой пояс</p></div></div><SettingsForm profile={profile} /></section><section className="rounded-[var(--radius-card)] border border-border bg-panel p-5 shadow-[var(--shadow-panel)]"><div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-danger/10 text-danger"><LogOut aria-hidden className="size-5" /></span><div><h2 className="text-lg font-semibold">Аккаунт</h2><p className="mt-1 text-sm text-muted-foreground">Завершить текущий сеанс</p></div></div><form action={signOutAction}><Button className="w-full border-danger/30 text-danger hover:bg-danger/10 hover:text-danger" variant="outline" type="submit"><LogOut aria-hidden className="size-4" />Выйти из аккаунта</Button></form></section><section className="flex min-h-16 items-center gap-3 rounded-[var(--radius-card)] border border-border bg-panel px-4 shadow-[var(--shadow-panel)]"><span className="grid size-10 place-items-center rounded-xl bg-muted text-primary"><Palette aria-hidden className="size-5" /></span><span><span className="block text-sm font-semibold">Kapot Money</span><span className="mt-0.5 block text-xs text-muted-foreground">Личный финансовый учёт</span></span></section></PageContainer>;
}

function MoreLink({ href, title, icon: Icon }: { href: string; title: string; icon: typeof WalletCards }) { return <Link href={href} className="flex min-h-16 items-center gap-3 border-b border-border px-4 transition hover:bg-muted"><span className="grid size-10 place-items-center rounded-xl bg-muted text-primary"><Icon aria-hidden className="size-5" /></span><span className="flex-1 text-sm font-semibold">{title}</span><ChevronRight aria-hidden className="size-5 text-muted-foreground" /></Link>; }
